import 'package:firebase_core/firebase_core.dart';

/// The marker the committed `lib/firebase_options.dart` ships instead of a real
/// Firebase project. Written both bare and wrapped in angle brackets, so match
/// on a substring rather than equality.
const String firebaseOptionsPlaceholderMarker = 'THIS_IS_AUTOGENERATED';

/// Whether any supplied option is still a committed placeholder.
///
/// Optional fields may be absent, but leaving a marker in a supplied field
/// (such as the web measurement ID) also means configuration is incomplete.
///
/// Worth checking before [Firebase.initializeApp]: on Apple platforms
/// `FIRApp` validates the app ID and raises an Objective-C exception on a
/// malformed one. That exception crosses the platform channel uncaught, so it
/// takes the process down rather than surfacing as a Dart error the caller
/// could handle.
bool isPlaceholderFirebaseOptions(FirebaseOptions options) =>
    options.asMap.values.any(
      (value) =>
          value != null && value.contains(firebaseOptionsPlaceholderMarker),
    );
