import 'package:web_dex/model/wallet.dart';

/// Why the app is about to reveal a receive address.
///
/// Carried through to the interstitial so its copy can name the thing the user
/// was doing, rather than appearing as a context-free interruption.
enum SeedBackupGateReason {
  /// A receive address or QR is about to be shown.
  receiveAddress,

  /// A receive address is about to be copied to the clipboard.
  copyAddress,

  /// The NFT receive screen is opening.
  nftReceive,
}

/// Whether funding this wallet should be interrupted to warn about backup.
///
/// Pure and Flutter-free so the decision is table-testable without a widget
/// tree - the mistake this replaces was exactly that the check lived inside a
/// bloc, where it could only ever be applied to one screen.
///
/// The rules, in order:
///
/// * No signed-in wallet - nothing to reveal, so nothing to gate.
/// * Hardware wallets - the backup ceremony happened on the device and there is
///   no mnemonic the app could show. Without this, a failed `has_backup`
///   metadata write would strand a Trezor user behind a modal that cannot
///   possibly complete.
/// * Test coins - carries the existing `!coin.isTestCoin` rule (previously
///   applied only to NFT receive) across every surface. Testnet value is zero,
///   and gating it would teach users the interstitial is noise.
/// * Otherwise, gate whenever the seed has not been backed up.
///
/// Note this is deliberately a no-op for typed-seed imports: those set
/// `hasBackup: true` at import time because the user demonstrably has the
/// words in front of them. The population left is the one that has never seen
/// a recovery phrase at all - wallets generated by the app, encrypted-file
/// imports, and legacy migrations.
bool seedBackupGateRequired({
  required Wallet? wallet,
  bool isTestCoin = false,
}) {
  if (wallet == null) return false;
  if (wallet.config.type == WalletType.trezor) return false;
  if (isTestCoin) return false;
  return !wallet.config.hasBackup;
}

/// Whether the wallet's seed was generated by the app rather than supplied by
/// the user.
///
/// Drives the stronger interstitial copy: a generated wallet's words have never
/// been displayed, so "these are new words" is news, and it is the signal that
/// catches someone who meant to restore an existing wallet and was routed into
/// creating a fresh one instead.
bool seedWasGeneratedForUser(Wallet? wallet) =>
    wallet?.config.provenance == WalletProvenance.generated;
