import 'dart:convert';

import 'package:easy_localization/easy_localization.dart';
import 'package:feedback/feedback.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:logging/logging.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:web_dex/app_config/app_config.dart';
import 'package:web_dex/generated/codegen_loader.g.dart';
import 'package:web_dex/services/feedback/feedback_env.dart';

// The environment variables can be set for the build using a .env file,
// see .env.example, or by using the following command for example:
// flutter build web --dart-define TRELLO_API_KEY=YOUR_KEY_HERE --dart-define TRELLO_TOKEN=YOUR_TOKEN_HERE --dart-define TRELLO_BOARD_ID=YOUR_BOARD_ID_HERE --dart-define TRELLO_LIST_ID=YOUR_LIST_ID_HERE

// The following environment variables must be set in your .env file (see .env.example):
// TRELLO_API_KEY: Your Trello API key
// TRELLO_TOKEN: Your Trello API token
// TRELLO_BOARD_ID: The ID of the Trello board where feedback will be sent
// TRELLO_LIST_ID: The ID of the Trello list where feedback will be sent

// The Trello API key can be obtained by going to the Power-Ups console:
// https://trello.com/power-ups/admin

// The Trello API token can be re-generated by going to:
// https://trello.com/1/authorize?expiration=never&name=Komodo%20Wallet%20Feedback&scope=read,write&response_type=token&key=YOUR_API_KEY
// If you have trouble for that, there will be an option in the power-up
// console to generate the link.
// The Trello board ID and list ID can be obtained by going to the Trello board
// and adding `.json` to the end of the URL.

class FeedbackService {
  final String apiKey;
  final String token;
  final String boardId;
  final String listId;

  static final _log = Logger('FeedbackService');

  FeedbackService({
    required this.apiKey,
    required this.token,
    required this.boardId,
    required this.listId,
  });

  /// Checks if the required environment variables are available using --dart-define
  static bool hasEnvironmentVariables() {
    final requiredVars = {
      'TRELLO_API_KEY': const String.fromEnvironment('TRELLO_API_KEY'),
      'TRELLO_TOKEN': const String.fromEnvironment('TRELLO_TOKEN'),
      'TRELLO_BOARD_ID': const String.fromEnvironment('TRELLO_BOARD_ID'),
      'TRELLO_LIST_ID': const String.fromEnvironment('TRELLO_LIST_ID')
    };

    final missingVars = requiredVars.entries
        .where((e) => e.value.isEmpty)
        .map((e) => e.key)
        .toList();

    if (missingVars.isNotEmpty) {
      _log.fine(
        'Some environment variables not defined with --dart-define: ${missingVars.join(", ")}',
      );
      return false;
    }

    return true;
  }

  /// Creates a FeedbackService instance using either:
  /// 1. Environment variables from .env file via FeedbackEnv
  /// 2. Or falls back to --dart-define variables
  /// Returns null if no environment variables are available from either source
  static FeedbackService? fromEnvironment() {
    // First try .env file through Envied
    final bool hasEnvFile = FeedbackEnv.hasAllVariables();

    if (hasEnvFile) {
      _log.fine('Using environment variables from .env file');
      return FeedbackService(
        apiKey: FeedbackEnv.apiKey!,
        token: FeedbackEnv.token!,
        boardId: FeedbackEnv.boardId!,
        listId: FeedbackEnv.listId!,
      );
    }

    // Fall back to --dart-define variables if .env isn't complete
    final bool hasDartDefineVars = hasEnvironmentVariables();

    if (hasDartDefineVars) {
      _log.fine('Using environment variables from --dart-define');
      return FeedbackService(
        apiKey: const String.fromEnvironment('TRELLO_API_KEY'),
        token: const String.fromEnvironment('TRELLO_TOKEN'),
        boardId: const String.fromEnvironment('TRELLO_BOARD_ID'),
        listId: const String.fromEnvironment('TRELLO_LIST_ID'),
      );
    }

    // Try mixed approach - use variables from wherever they're defined
    final String? apiKey = FeedbackEnv.hasApiKey()
        ? FeedbackEnv.apiKey
        : const String.fromEnvironment('TRELLO_API_KEY');

    final String? token = FeedbackEnv.hasToken()
        ? FeedbackEnv.token
        : const String.fromEnvironment('TRELLO_TOKEN');

    final String? boardId = FeedbackEnv.hasBoardId()
        ? FeedbackEnv.boardId
        : const String.fromEnvironment('TRELLO_BOARD_ID');

    final String? listId = FeedbackEnv.hasListId()
        ? FeedbackEnv.listId
        : const String.fromEnvironment('TRELLO_LIST_ID');

    // Check if we have all variables from one source or another
    if (apiKey?.isNotEmpty == true &&
        token?.isNotEmpty == true &&
        boardId?.isNotEmpty == true &&
        listId?.isNotEmpty == true) {
      _log.fine('Using mixed environment variables from .env and dart-define');
      return FeedbackService(
        apiKey: apiKey!,
        token: token!,
        boardId: boardId!,
        listId: listId!,
      );
    }

    _log.warning(
      'Missing required environment variables for feedback service from all sources',
    );
    return null;
  }

  Future<void> handleFeedback(UserFeedback feedback) async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    final Map<String, dynamic> metadata = {
      ...packageInfo.data,
    };

    try {
      await submitFeedback(
        description: feedback.text,
        screenshot: feedback.screenshot,
        type: 'User Feedback',
        metadata: metadata,
      );

      final theme = Theme.of(scaffoldKey.currentContext!);

      ScaffoldMessenger.of(scaffoldKey.currentContext!).showSnackBar(
        SnackBar(
          content: Text(
            'Thank you! ${LocaleKeys.feedbackFormDescription.tr()}',
            style: theme.textTheme.bodyLarge?.copyWith(
              color: theme.colorScheme.onPrimaryContainer,
            ),
          ),
          backgroundColor: theme.colorScheme.primaryContainer,
          action: SnackBarAction(
            label: LocaleKeys.addMoreFeedback.tr(),
            textColor: theme.colorScheme.onPrimaryContainer,
            onPressed: () => scaffoldKey.currentContext!.showFeedback(),
          ),
          duration: const Duration(seconds: 5),
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
        ),
      );
    } catch (e, s) {
      _log.severe('Failed to submit feedback', e, s);
      rethrow;
    }
  }

  Future<void> submitFeedback({
    required String description,
    required Uint8List screenshot,
    required String type,
    required Map<String, dynamic> metadata,
  }) async {
    try {
      // 1. Create the card
      final cardResponse = await http.post(
        Uri.parse('https://api.trello.com/1/cards'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'idList': listId,
          'key': apiKey,
          'token': token,
          'name': 'Feedback: $type',
          'desc': '''
Description:
$description

Device Info:
${metadata.entries.map((e) => '${e.key}: ${e.value}').join('\n')}
''',
        }),
      );

      if (cardResponse.statusCode != 200) {
        throw Exception(
            'Failed to create Trello card (${cardResponse.statusCode}): ${cardResponse.body}');
      }

      final cardId = jsonDecode(cardResponse.body)['id'];

      // 2. Attach the screenshot to the card
      final attachmentRequest = http.MultipartRequest(
        'POST',
        Uri.parse('https://api.trello.com/1/cards/$cardId/attachments'),
      );

      attachmentRequest.fields.addAll({
        'key': apiKey,
        'token': token,
      });

      attachmentRequest.files.add(
        http.MultipartFile.fromBytes(
          'file',
          screenshot,
          filename: 'screenshot.png',
        ),
      );

      final attachmentResponse = await attachmentRequest.send();
      final streamedResponse =
          await http.Response.fromStream(attachmentResponse);

      if (streamedResponse.statusCode != 200) {
        throw Exception(
          'Failed to attach screenshot (${streamedResponse.statusCode}): ${streamedResponse.body}',
        );
      }
    } catch (e, s) {
      _log.shout('Error in submitFeedback', e, s);
      rethrow;
    }
  }
}

extension BuildContextShowFeedback on BuildContext {
  /// Shows the feedback dialog if the feedback service is available.
  /// Does nothing if the feedback service is not configured.
  void showFeedback() {
    final feedbackService = FeedbackService.fromEnvironment();
    if (feedbackService == null) {
      debugPrint(
          'Feedback dialog not shown: feedback service is not configured');
      return;
    }

    BetterFeedback.of(this).show(
      feedbackService.handleFeedback,
    );
  }

  /// Returns true if feedback functionality is available from either .env or --dart-define
  bool get isFeedbackAvailable {
    return FeedbackEnv.hasAllVariables() ||
        FeedbackService.hasEnvironmentVariables();
  }
}
