name: komodo_cex_market_data
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none # publishable packages should not have git dependencies

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: 1.2.2 # dart.dev

  equatable: 2.0.7
      
  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive:
    git:
      url: https://github.com/KomodoPlatform/hive.git
      path: hive/
      ref: 470473ffc1ba39f6c90f31ababe0ee63b76b69fe #2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0 # flutter.dev
  test: ^1.24.0
