name: app_theme
description: App theme.
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.35.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8 # flutter.dev
