name: Devcontainer Build

on:
  push:
    branches: [ build/devcontainer-reuse-docker-images ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base android-sdk image
        run: |
          docker build -t komodo/android-sdk:35 -f .docker/android-sdk.dockerfile .

      - name: Build komodo-wallet dev image
        run: |
          docker build -t komodo/komodo-wallet:latest -f .docker/komodo-wallet-android.dockerfile .


